const PROJECTS = {
    tax: {
        icon: '📄',
        name: 'Tax Document Processor',
        category: 'AI Document Automation',
        problem: 'Tax offices spend 1–2 hours per client manually sorting incoming PDFs, identifying each document type, and hand-entering data into review spreadsheets — a repetitive, error-prone process that bottlenecks staff during busy season.',
        solution: 'A desktop application that accepts a client\'s PDF documents, uses AI to read and extract all relevant data, and automatically produces a fully organized output package: a populated review workbook, renamed source files, and a structured client folder — ready for staff review in under 5 minutes.',
        results: [
            '95%+ reduction in per-client processing time (1–2 hrs → ~5 min)',
            'Handles W-2s, 1099s, prior-year returns, and mixed document packets automatically',
            'Standardized output format eliminates manual filing inconsistencies',
            'Built with a hard-cap on AI usage costs — no runaway billing',
        ],
        tags: [
            { label: 'AWS Bedrock', cls: 't-blue' },
            { label: 'Claude Sonnet (AI)', cls: 't-blue' },
            { label: 'PDF Extraction', cls: 't-green' },
            { label: 'Excel Automation', cls: 't-orange' },
            { label: 'Desktop App', cls: 't-purple' },
        ],
        github: 'https://github.com/thejdog2000/tax_document_processor',
    },
    orchestrator: {
        icon: '🤖',
        name: 'AI Orchestrator',
        category: 'AI Automation System',
        problem: 'Managing 6 active software projects simultaneously means constant context-switching and never enough hours to make meaningful progress on all of them. Hiring help for every project isn\'t feasible.',
        solution: 'An autonomous overnight system that runs AI-driven development tasks across all 6 projects while you sleep. A quality review layer checks every change before it\'s queued. Each morning, a digest summarizes what was built — and nothing gets applied without explicit approval.',
        results: [
            '6 projects developed in parallel with ~45 minutes of daily oversight',
            'Every code change is reviewed by a second AI layer before reaching the human',
            'Hard monthly cost cap enforced in code — halts automatically at the limit',
            'Demonstrates how AI can act as an overnight workforce with human-in-the-loop control',
        ],
        tags: [
            { label: 'LLM Orchestration', cls: 't-blue' },
            { label: 'Local AI (Ollama)', cls: 't-blue' },
            { label: 'Task Scheduling', cls: 't-purple' },
            { label: 'Quality Automation', cls: 't-green' },
            { label: 'Cost Controls', cls: 't-orange' },
        ],
        github: null,
        private: true,
    },
    meridian: {
        icon: '🌐',
        name: 'Meridian',
        category: 'Full-Stack Web Application',
        problem: 'Building a modern, fully featured community platform — with user accounts, social feeds, direct messaging, events, and moderation — typically requires a full engineering team and months of development.',
        solution: 'A complete social platform built and deployed solo: editorial landing page, social feed with interactions, direct messaging, fashion events with RSVP, category discovery, user profiles, and a full admin moderation dashboard. Production-ready with authentication, email verification, image uploads, and real-time notifications.',
        results: [
            '15+ authenticated routes built and deployed as a single engineer',
            'Full admin moderation system: reports, warnings, bans',
            'Secure authentication with email verification and password reset',
            'Demonstrates ability to own an entire product from database to deployed UI',
        ],
        tags: [
            { label: 'Web Application', cls: 't-blue' },
            { label: 'Database Design', cls: 't-green' },
            { label: 'User Authentication', cls: 't-purple' },
            { label: 'Cloud Storage', cls: 't-orange' },
            { label: 'Real-time Features', cls: 't-pink' },
        ],
        github: null,
        private: true,
    },
    gamma: {
        icon: '📈',
        name: 'Gamma Exposure Tool',
        category: 'Financial Analytics',
        problem: 'Retail options traders lack access to the dealer positioning data and gamma exposure analysis that institutional desks use to identify key price levels and intraday magnetism zones — giving institutions a significant informational edge.',
        solution: 'An analysis dashboard that calculates and visualizes dealer gamma exposure for SPX 0DTE options, surfaces key strike levels, and includes a backtesting engine to validate signal effectiveness over historical data. Used in live trading.',
        results: [
            'Surfaces institutional-grade positioning data for retail traders',
            'Overnight batch analysis pipeline runs automatically before market open',
            'Backtesting engine validates signal quality before live application',
            'Part of a live trading system with real capital under management',
        ],
        tags: [
            { label: 'Financial Analytics', cls: 't-blue' },
            { label: 'Data Visualization', cls: 't-orange' },
            { label: 'Backtesting Engine', cls: 't-purple' },
            { label: 'Automated Pipeline', cls: 't-green' },
        ],
        github: 'https://github.com/thejdog2000/gammatool',
    },
    travelsim: {
        icon: '🗺️',
        name: 'TravelSim',
        category: 'AI Learning Application',
        problem: 'Traditional language learning apps are repetitive and decontextualized — users memorize vocabulary and grammar rules in isolation, without ever practicing the real-world scenarios where the language actually matters.',
        solution: 'An immersive language learning app that places users inside 3D simulations of real environments — izakayas, train stations, markets — with contextual AI coaching for Japanese and Spanish. Users learn by doing, not drilling.',
        results: [
            'Scenario-based learning grounded in realistic environments',
            'AI coaching adapts to user responses in real time',
            'Built primarily through an autonomous AI development pipeline — itself a proof of concept for agentic software development',
        ],
        tags: [
            { label: 'AI Coaching', cls: 't-blue' },
            { label: 'LLM Integration', cls: 't-blue' },
            { label: '3D Environments', cls: 't-purple' },
            { label: 'Web Application', cls: 't-green' },
        ],
        github: 'https://github.com/thejdog2000/TravelSim',
    },
    trade: {
        icon: '⚡',
        name: 'Trade Alert MVP',
        category: 'Automation & Real-time Systems',
        problem: 'Manually checking for trading setups overnight is impractical — by the time a trader wakes up, entry windows have already opened or closed. Without automation, actionable setups get missed.',
        solution: 'A real-time alert engine that monitors nightly market conditions against configurable setup criteria, fires alerts when setups match, and integrates into a broader live algorithmic trading system with positions under active management.',
        results: [
            'Automated overnight monitoring replaces manual pre-market checks',
            'Configurable alert rules based on backtested signal criteria',
            'Integrated into a live trading system with real capital deployed',
        ],
        tags: [
            { label: 'Real-time Monitoring', cls: 't-blue' },
            { label: 'REST API', cls: 't-green' },
            { label: 'Algorithmic Trading', cls: 't-purple' },
            { label: 'Automation', cls: 't-orange' },
        ],
        github: null,
    },
    ironforge: {
        icon: '⚔️',
        name: 'IronForge',
        category: 'Game Development',
        problem: 'Merging real-time strategy and first-person shooter gameplay requires deeply custom AI systems, resource management logic, and a combat engine that can shift modes without breaking the player\'s experience.',
        solution: 'A Unity game with custom AI-controlled units, RTS base-building mechanics, and first-person ground combat — two distinct gameplay modes unified in a single engine. AI-assisted code generation was used to accelerate complex systems development.',
        results: [
            'Multi-mode game engine: top-down strategy layer + FPS ground combat',
            'Custom unit AI and resource management systems',
            'Demonstrates ability to architect complex interactive systems from scratch',
        ],
        tags: [
            { label: 'Game Engine', cls: 't-orange' },
            { label: 'AI-Assisted Dev', cls: 't-blue' },
            { label: 'Systems Design', cls: 't-green' },
            { label: 'Interactive Simulation', cls: 't-purple' },
        ],
        github: 'https://github.com/thejdog2000/IronForge',
    },
    dreadfall: {
        icon: '🎮',
        name: 'Dreadfall',
        category: 'Game Modding',
        problem: 'Extending an existing game engine with entirely new content — custom enemies, world generation rules, loot tables, and game mechanics — requires deep knowledge of the engine\'s event systems and packaging framework.',
        solution: 'A full Minecraft mod with dark fantasy / horror theming: custom mobs with new behaviors, procedural world generation, loot systems, and mechanics distributed via the Minecraft Forge framework.',
        results: [
            'Custom enemy AI and behavior systems built from scratch',
            'Procedural world generation integrated into the existing engine',
            'Packaged and distributable via standard Minecraft Forge tooling',
        ],
        tags: [
            { label: 'Game Modding', cls: 't-blue' },
            { label: 'Custom AI Behaviors', cls: 't-green' },
            { label: 'Procedural Generation', cls: 't-purple' },
            { label: 'Java', cls: 't-orange' },
        ],
        github: 'https://github.com/thejdog2000/minecraft_dreadfall',
    },
};
